function T = LH2Body(E)
    % Calculate roll, pitch, and yaw angles
    Roll = E(1); %{rad} Roll angle
    Pitch = E(2); %{rad} Pitch angle
    Yaw = E(3); %{rad} Yaw angle

    % Transformation matrices for rotations
    T1 = [...
        1,          0,         0; ...
        0,  cos(Roll), sin(Roll); ...
        0, -sin(Roll), cos(Roll)]; %Matrix that rotates about the 1-axis by Roll angle

    T2 = [ ...
        cos(Pitch), 0, -sin(Pitch); ...
                 0, 1,           0; ...
        sin(Pitch), 0,  cos(Pitch)]; %Matrix that rotates about the 2-axis by Pitch angle

    T3 = [ ...
         cos(Yaw), sin(Yaw), 0; ...
        -sin(Yaw), cos(Yaw), 0; ...
                0,        0, 1]; %Matrix that rotates about the 3-axis by Yaw angle

    T = T1 * T2 * T3; %Matrix that transforms vectors from LH coordinates to Body coordinates
end